apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    character-set-server = utf8
    log-bin
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    character-set-server = utf8
    super-read-only
